% Create a linearArray with patchMicrostrip element.
% Generated by MATLAB(R) 9.12 and Antenna Toolbox 5.2.
% Generated on: 17-Nov-2022 22:32:36

%% Array Properties 

patch = design(patchMicrostrip, 915*1e6);
% patchArray = design(linearArray('Element', patch), 915*1e6, patch);
patchArray = linearArray;
patchArray.Element = patch;
patchArray.NumElements = 4;
patchArray.ElementSpacing = (3e8/915e6);

pattern(patchArray,915e6);

%% Array Analysis 
% Show for linearArray


% pattern(patchArray,915e6)

patchArray = rectangularArray;
patchArray.Element = patch;
patchArray.Size = [2 2];
patchArray.RowSpacing = (3e8/915e6);
patchArray.ColumnSpacing = (3e8/915e6);
figure;
show(patchArray) 
% Layout for linearArray
figure;
layout(patchArray) 

figure;
patchArray.PhaseShift = phaseShift(patchArray,915e6,[0;60]);
pattern(patchArray,915e6);
